[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  VITE_API_URL = "https://smarthabitgarden-backend.onrender.com"

# Redirect all routes to index.html for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
